services:
  php:
    image: naegato/php-symfony:php8.3-postgres-2
    volumes:
      - ./:/srv:cached
    hostname: streami-php
    container_name: streami-php
    user: 1000:1000
    depends_on:
      - db

  web:
    build:
      context: ./docker/nginx
    volumes:
      - .:/srv:cached
    hostname: streami-web
    environment:
      fastcgi_pass: streami-php:9000
    depends_on:
      - php
    ports:
      - 8000:80

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${DB_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/postgresql/data:rw

#  adminer:
#    image: adminer:4.8.1

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
